services:
  job:
    image: programic/dfirewall-cloudflare:latest
    environment:
      AUTH_EMAIL: <Cloudflare Email>
      AUTH_KEY: <Cloudflare Key>
      ACCOUNT_ID: <Cloudflare Account ID>
      LIST_ID: <Cloudflare List ID>
      JOB_INTERVAL: "*/5 * * * *"
    build:
      context: .
      dockerfile: ./job.dockerfile

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30